[toolchain]
channel = "1.76.0-x86_64-unknown-linux-gnu" 
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
components = ["rustfmt", "clippy"]

#channel = "nightly-2023-04-25" nightly-2023-10-14 nightly-2023-09-05

